[package]
name = "tcpchat"
version = "0.1.0"
authors = ["Alex Auvolat <alex.auvolat-bernstein@inria.fr>"]

[dependencies]
bufstream = ""

tokio = "0.1"
tokio-io = "0.1"
futures = "0.1"
bytes = "0.4"
mio = "0.6"
